# Backend Deployment and Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Redis__ConnectionString: "redis:6379"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lzai-backend
  namespace: default
  labels:
    app: lzai-backend
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lzai-backend
  template:
    metadata:
      labels:
        app: lzai-backend
    spec:
      containers:
      - name: backend
        image: <ACR_LOGIN_SERVER>/lzai-backend:latest  # Replace with your ACR
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: lzai-backend
  namespace: default
  labels:
    app: lzai-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: lzai-backend