# Frontend Deployment and Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  REACT_APP_API_URL: "http://lzai-backend/api"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lzai-frontend
  namespace: default
  labels:
    app: lzai-frontend
    component: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lzai-frontend
  template:
    metadata:
      labels:
        app: lzai-frontend
    spec:
      containers:
      - name: frontend
        image: <ACR_LOGIN_SERVER>/lzai-frontend:latest  # Replace with your ACR
        ports:
        - containerPort: 80
          name: http
        envFrom:
        - configMapRef:
            name: frontend-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: lzai-frontend
  namespace: default
  labels:
    app: lzai-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: lzai-frontend